repos:

# Automatically sort imports
- repo: https://github.com/PyCQA/isort
  rev: 5.6.4
  hooks:
  - id: isort

# Automatic source code formatting
- repo: https://github.com/psf/black
  rev: 21.4b2
  hooks:
  - id: black
    args: [--safe, --quiet]
    files: \.pyi?$|SConscript$|^libtbx_config$
    types: [file]

# Linting
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-comprehensions==3.5.0']

# Syntax check and some basic flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-ast
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=200']
  - id: no-commit-to-branch
    args: ['--branch', 'master']
    name: "Don't commit to 'master'"

- repo: local
  hooks:
  - id: no-images
    name: Check for image files
    entry: >
      Images for documentation should go into the documentation repository
      https://github.com/dials/dials.github.io
    language: fail
    files: '.*\.png$'
