repos:

# Automatically sort imports
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort

# Automatic source code formatting
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
    args: [--safe, --quiet]
    files: \.pyi?$|SConscript$|^libtbx_config$
    types: [file]

# Linting
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-comprehensions==3.8.0']

# Give a specific warning for added image files
- repo: local
  hooks:
  - id: no-images
    name: Check for image files
    entry: >
      Images for documentation should go into the documentation repository
      https://github.com/dials/dials.github.io
    language: fail
    files: '.*\.png$'

# Syntax validation and some basic sanity checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-ast
  - id: check-yaml
    args: ['--allow-multiple-documents']
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=200']
  - id: no-commit-to-branch
    name: "Don't commit to 'main'"
