[tool.black]
include='\.pyi?$|/SConscript$|/libtbx_config$'

[tool.towncrier]
package = "dials"
package_dir = ".."
filename = "CHANGELOG.rst"
issue_format = "`#{issue} <https://github.com/dials/dials/issues/{issue}>`_"

[tool.isort]
sections="FUTURE,STDLIB,THIRDPARTY,CCTBX,FIRSTPARTY,LOCALFOLDER"
known_firstparty="dials_*"
known_cctbx="boost,boost_adaptbx,cbflib_adaptbx,cctbx,chiltbx,clipper_adaptbx,cma_es,cootbx,crys3d,cudatbx,dxtbx,fable,fast_linalg,fftw3tbx,gltbx,iota,iotbx,libtbx,mmtbx,omptbx,prime,rstbx,scitbx,simtbx,smtbx,spotfinder,tbxx,ucif,wxtbx,xfel"
profile="black"

