jobs:
- job: macos
  pool:
    vmImage: macOS-latest
  condition: eq(stageDependencies.prepare.setup.outputs['constants.NEWSFRAGMENT_WAITING'], 'false')
  variables:
    CURRENT_WEEK: $[ stageDependencies.prepare.setup.outputs['constants.CURRENT_WEEK'] ]
    TODAY_ISO: $[ stageDependencies.prepare.setup.outputs['constants.TODAY_ISO'] ]
    SOURCE_BRANCH: $[ stageDependencies.prepare.setup.outputs['constants.BUILD_SOURCEBRANCH'] ]
  strategy:
    matrix:
      python36:
        PYTHON_VERSION: 3.6
#     python37:
#       PYTHON_VERSION: 3.7
#     python38:
#       PYTHON_VERSION: 3.8
  timeoutInMinutes: 150

  steps:
  - template: unix-build.yml
    parameters:
      conda_environment: .conda-envs/macos.txt
