jobs:
- job: linux
  pool:
    vmImage: ubuntu-20.04
  condition: eq(dependencies.prepare.outputs['setup.constants.NEWSFRAGMENT_WAITING'], 'false')
  variables:
    CURRENT_WEEK: $[ dependencies.prepare.outputs['setup.constants.CURRENT_WEEK'] ]
    TODAY_ISO: $[ dependencies.prepare.outputs['setup.constants.TODAY_ISO'] ]
  strategy:
    matrix:
      python36:
        PYTHON_VERSION: 3.6
#      python37:
#        PYTHON_VERSION: 3.7
#      python38:
#        PYTHON_VERSION: 3.8
  timeoutInMinutes: 150

  steps:
  # Dependencies required for building gltbx
  - script: |
      sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
    displayName: Install dependencies

  - template: unix-build.yml
    parameters:
      conda_environment: .conda-envs/linux.txt
