jobs:
- job: windows
  pool:
    vmImage: windows-latest
  variables:
    CURRENT_WEEK: $[ stageDependencies.prepare.setup.outputs['constants.CURRENT_WEEK'] ]
    TODAY_ISO: $[ stageDependencies.prepare.setup.outputs['constants.TODAY_ISO'] ]
  strategy:
    matrix:
      python37:
        PYTHON_VERSION: 3.7
#     python38:
#       PYTHON_VERSION: 3.8
#     python39:
#       PYTHON_VERSION: 3.9
  timeoutInMinutes: 150

  steps:

  - template: windows-build.yml
    parameters:
      conda_environment: .conda-envs/windows.txt
