# Variables:
#   CACHE_VERSION: unique cache identifier
#   CURRENT_WEEK: weekly changing cache identifier
#   PYTHON_VERSION: string in the form of "3.x"
#   TODAY_ISO: today's date in ISO format, eg. "20200531"

steps:

# Obtain a shallow clone of the DIALS repository.
# DIALS will not be able to report proper version numbers
- checkout: self
  path: ./dials-checkout
  fetchDepth: 1
  displayName: Checkout $(Build.SourceBranch)

# Get all other source repositories from cache if available
# Allow day-to-day incremental cache updates
# Flush the cache once a week and whenever the bootstrap script is modified
- task: Cache@2
  inputs:
    key: '"repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | installer/bootstrap.py | "$(TODAY_ISO)"'
    restoreKeys: |
      "repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | installer/bootstrap.py
    path: $(Pipeline.Workspace)/modules
    cacheHitVar: REPOSITORIES_CACHED
  displayName: Restore repository cache

# If other source repositories are not cached then download
# them using the bootstrap script
- bash: |
    set -e
    mkdir -p modules
    ln ../dials-checkout modules/dials -nsf
    python modules/dials/installer/bootstrap.py update
  displayName: Repository checkout (initial)
  workingDirectory: $(Pipeline.Workspace)
  condition: eq(variables.REPOSITORIES_CACHED, 'false')

# Update the cctbx_project and dxtbx repositories now,
# unless they were just freshly cloned
- bash: |
    set -e
    for repository in cctbx_project dxtbx; do
      if [ ! -e $(Pipeline.Workspace)/modules/${repository} ]; then
        echo Cloning ${repository} from scratch
        git clone https://github.com/cctbx/${repository}.git --depth=1 $(Pipeline.Workspace)/modules/${repository}
      fi

      echo Checking out latest ${repository} commit
      cd $(Pipeline.Workspace)/modules/${repository} || exit 1
      git fetch origin master --depth=1 || exit 2
      git checkout FETCH_HEAD || exit 3
      echo -n "${repository} is at commit "
      git show --oneline -s --no-abbrev-commit || exit 4
    done
  displayName: Repository update (incremental)
  workingDirectory: $(Pipeline.Workspace)
  condition: ne(variables.REPOSITORIES_CACHED, 'false')

# Get a ready-made DIALS conda environment from cache if available
# Allow day-to-day incremental cache updates
# Flush the cache once a week and whenever the environment specification is modified
# Cache is not shared across operating systems and python versions
- task: Cache@2
  inputs:
    key: '"base" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)" | "$(PYTHON_VERSION)" | .conda-envs/linux.txt | "$(TODAY_ISO)"'
    restoreKeys: |
      "base" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)" | "$(PYTHON_VERSION)" | .conda-envs/linux.txt
    path: $(Pipeline.Workspace)/conda_base
    cacheHitVar: BASE_CACHED
  displayName: Restore environment cache

# If the conda environment could not be loaded from cache then
# create a new one using the bootstrap script
- script: |
    python modules/dials/installer/bootstrap.py base --python $(PYTHON_VERSION)
  displayName: Create python $(PYTHON_VERSION) environment
  workingDirectory: $(Pipeline.Workspace)
  condition: eq(variables.BASE_CACHED, 'false')

# Get a ready-made DIALS build directory from cache if available
# Allow day-to-day incremental cache updates
# Flush the cache once a week and whenever the environment specification
# or the bootstrap script is modified.
# Cache is not shared across operating systems and python versions
- task: Cache@2
  inputs:
    key: '"build" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)" | "$(PYTHON_VERSION)" | installer/bootstrap.py | .conda-envs/linux.txt | "$(TODAY_ISO)"'
    restoreKeys: |
      "build" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)" | "$(PYTHON_VERSION)" | installer/bootstrap.py | .conda-envs/linux.txt
    path: $(Pipeline.Workspace)/build
    cacheHitVar: BUILD_CACHED
  displayName: Restore cached build

# If the build directory could not be loaded from cache then
# create a new one using the bootstrap script
- script: |
    python modules/dials/installer/bootstrap.py build
  displayName: DIALS build (initial)
  workingDirectory: $(Pipeline.Workspace)
  condition: eq(variables.BUILD_CACHED, 'false')

# If the build directory was loaded (or kick-started) from cache then
# do an incremental build
- bash: |
    set -e
    . setpaths.sh
    make reconf
  displayName: DIALS build (incremental)
  workingDirectory: $(Pipeline.Workspace)/build
  condition: ne(variables.BUILD_CACHED, 'false')

# Ensure we are using up-to-date testing packages.
# Extract the dials-data version so we can correctly cache regression data.
- bash: |
    set -e
    . build/setpaths.sh
    libtbx.conda install -p conda_base -y dials-data pytest-azurepipelines
    dials.data info -v
    echo "##vso[task.setvariable variable=DIALS_DATA_VERSION_FULL]$(dials.data info -v | grep version.full)"
    echo "##vso[task.setvariable variable=DIALS_DATA_VERSION]$(dials.data info -v | grep version.major)"
    #                                                                this is a bug in dials-data ^^^^^
    mkdir -p data
  displayName: Install additional packages
  workingDirectory: $(Pipeline.Workspace)

# Retrieve the regression data from cache if possible
# The cache allows day-to-day incremental updates, which is relevant only if
# tests are added that refer to datasets in dials-data that were not previously
# referred to.
# New versions of dials-data also lead to cache updates, kick-started from the
# previous cache version.
# The cache is shared across operating systems and python versions, and flushed
# once a week and for dials-data major and minor releases (eg. 2.0->2.1).
- task: Cache@2
  inputs:
    key: '"data" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(DIALS_DATA_VERSION)" | "$(TODAY_ISO)" | "$(DIALS_DATA_VERSION_FULL)"'
    restoreKeys: |
      "data" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(DIALS_DATA_VERSION)" | "$(TODAY_ISO)"
      "data" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(DIALS_DATA_VERSION)"
    path: $(Pipeline.Workspace)/data
  displayName: Restore regression data cache

# Finally, run the full regression test suite
- bash: |
    set -e
    export DIALS_DATA=$(pwd)/data
    . build/setpaths.sh
    cd modules/dials
    libtbx.pytest -ra -n auto --runslow --regression || echo "##vso[task.complete result=Failed;]Some tests failed"
  displayName: Run tests
  workingDirectory: $(Pipeline.Workspace)

# If the downloaded repositories are to be cached then clean them up before the
# snapshot is made
- script: |
    echo Preparing cache
    for repository in modules/*; do
      if [ -e ${repository}/.git ]; then
        echo Cleaning directory ${repository}
        cd ${repository}
        git reset --hard HEAD
        git clean -dffxq
        git repack -a -d
        cd -
      fi
    done
    ls -la modules
  displayName: Preparing cache
  workingDirectory: $(Pipeline.Workspace)
  condition: ne(variables.REPOSITORIES_CACHED, 'true')
